In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5],dtype=np.int64)

In [5]:
arr1

array([1, 2, 3, 4, 5], dtype=int64)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr3=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])

In [10]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [11]:
arr3=np.array([[[1,2,3,4],[5,6,7,8,]],[[9,10,11,12],[13,14,15,16]]])

In [12]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [13]:
arr3.ndim

3

In [14]:
arr=np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[13,14,15,16]]
])

In [15]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [16]:
arr.ndim

3

In [17]:
arr.shape

(2, 2, 4)

In [18]:
arr.size

16

In [20]:
arr4=np.array([[[[1,2,3],[4,5,6]]],[[[7,8,9],[10,11,12]]]])

In [21]:
arr4

array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
array1=np.ones((3,4))

In [24]:
array1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Empty array

In [25]:
e_array=np.empty((3,4))

In [26]:
e_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
e_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
i_array1=np.identity(3)

In [29]:
i_array1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
i_array2=np.eye(2)

In [31]:
i_array2

array([[1., 0.],
       [0., 1.]])

In [32]:
rand_array1=np.random.rand(5)

In [33]:
rand_array1

array([0.44949466, 0.98132519, 0.80112478, 0.41441524, 0.98658279])

In [34]:
rand_array1=np.random.rand(3,4)

In [35]:
rand_array1

array([[0.18564405, 0.01047513, 0.07794712, 0.46599796],
       [0.12830399, 0.92271014, 0.52255849, 0.48827638],
       [0.99297272, 0.90827346, 0.71354378, 0.86090432]])

In [36]:
range_array2=np.arange(10)

In [37]:
range_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
range_array2=np.arange(5,15,2)

In [39]:
range_array2

array([ 5,  7,  9, 11, 13])

In [41]:
bool_array=np.array([1,2,3,4,5])
condition=bool_array>3
print(condition)

[False False False  True  True]


In [42]:
f_array=np.full([2,3],15,dtype=int)

In [43]:
f_array

array([[15, 15, 15],
       [15, 15, 15]])

In [45]:
lin_array1=np.linspace(0,10,5)

In [46]:
lin_array1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [48]:
re_array1=np.linspace(10,20,6).reshape(2,3)

In [49]:
re_array1

array([[10., 12., 14.],
       [16., 18., 20.]])

In [50]:
re_array1=np.linspace(10,20,6).reshape(6,1)

In [51]:
re_array1

array([[10.],
       [12.],
       [14.],
       [16.],
       [18.],
       [20.]])

In [54]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [55]:
np.arange(100,300,5).size

40

In [56]:
np.arange(100,300,5).reshape(5,8)

array([[100, 105, 110, 115, 120, 125, 130, 135],
       [140, 145, 150, 155, 160, 165, 170, 175],
       [180, 185, 190, 195, 200, 205, 210, 215],
       [220, 225, 230, 235, 240, 245, 250, 255],
       [260, 265, 270, 275, 280, 285, 290, 295]])

In [57]:
arith_array=np.array([25,50,56,58])

In [58]:
arith_array

array([25, 50, 56, 58])

In [59]:
print(arith_array+5)

[30 55 61 63]


In [61]:
print(arith_array-5)

[20 45 51 53]


In [62]:
print(arith_array*2)

[ 50 100 112 116]


In [63]:
print(arith_array/4)

[ 6.25 12.5  14.   14.5 ]


In [65]:
ind_array1=np.array([1,2,3,4,5])
print(ind_array1)
print(ind_array1[0])
print(ind_array1[3])

[1 2 3 4 5]
1
4


In [66]:
print(ind_array1[1:4])

[2 3 4]


In [67]:
print(ind_array1[:3])

[1 2 3]


In [68]:
print(ind_array1[2:])

[3 4 5]


In [69]:
mod_array=np.array([10,20,30])
print(mod_array)
mod_array[1]=15
print(mod_array)

[10 20 30]
[10 15 30]


In [71]:
ind_array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
ind_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
print(ind_array2[0,1])

2


In [74]:
print(ind_array2[2,2])

9


In [75]:
print(ind_array2[1:3,0:2])

[[4 5]
 [7 8]]


In [4]:
ind_array3=np.array([[1,2,3],[4,5,6]])
print(ind_array3[0,1])

2


In [5]:
print(ind_array3[:,1])

[2 5]


In [2]:
import numpy as np

In [6]:
print(ind_array3[1,1:])

[5 6]


In [7]:
print(ind_array3[:2,:2])

[[1 2]
 [4 5]]


In [8]:
aggr_array=np.array([5,10,15,25])
print(aggr_array.sum())

55


In [9]:
print(aggr_array.sum(axis=0))

55


In [11]:
aggr_array1=np.array([[5,10,15,25]])
print(aggr_array1.sum(axis=1))

[55]


In [12]:
aggr_array2=np.array([[5,10,15,25],[10,20,30,40]])
print(aggr_array2.sum())

155


In [14]:
aggr_array2=np.array([[5,10,15,25],[10,20,30,40]])
print(aggr_array2.sum(axis=0))

[15 30 45 65]


In [15]:
aggr_array2=np.array([[5,10,15,25],[10,20,30,40]])
print(aggr_array2.sum(axis=1))

[ 55 100]


In [16]:
print(aggr_array2.min())

5


In [17]:
print(aggr_array2.max())

40


In [18]:
print(aggr_array2.mean())

19.375


In [19]:
print(aggr_array2.std())

11.02199505534275


In [20]:
join_array1=np.array([1,2,3])
join_array2=np.array([4,5,6])
join_result=np.concatenate((join_array1,join_array2))
print(join_result)

[1 2 3 4 5 6]


In [21]:
original_array=np.array([1,2,3,4,5,4,4])
search_item1=np.where(original_array==4)
print(search_item1)

(array([3, 5, 6], dtype=int64),)


In [22]:
search_item1=np.where(original_array==6)
print(search_item1)

(array([], dtype=int64),)


In [25]:
array_to_split=np.array([1,2,3,4,5,6])
splitted_array=np.array_split(array_to_split,3)
print(splitted_array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [26]:
splitted_array=np.array_split(array_to_split,5)
print(splitted_array)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [27]:
splitted_array=np.array_split(array_to_split,6)
print(splitted_array)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [28]:
splitted_array=np.array_split(array_to_split,7)
print(splitted_array)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [29]:
array_to_sort=np.array([3,2,0,1])
print(np.sort(array_to_sort))

[0 1 2 3]


In [30]:
print(np.sort(array_to_sort,axis=0))

[0 1 2 3]


In [31]:
sorted_array=np.sort(array_to_sort)
reversed_array=sorted_array[::-1]
print(reversed_array)

[3 2 1 0]


In [32]:
array_to_sort1=np.array([[3,2,0,1],[5,2,6,9]])
print(np.sort(array_to_sort1))

[[0 1 2 3]
 [2 5 6 9]]


In [33]:
print(np.sort(array_to_sort1,axis=1))

[[0 1 2 3]
 [2 5 6 9]]


In [34]:
print(np.sort(array_to_sort1,axis=0))

[[3 2 0 1]
 [5 2 6 9]]


In [35]:
array_to_sort1=np.array([[5,10,6,9],[3,20,0,1]])
print(np.sort(array_to_sort1,axis=0))

[[ 3 10  0  1]
 [ 5 20  6  9]]


In [38]:
array_to_reshape=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_array=array_to_reshape.reshape(4,3)
print(reshaped_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
reshaped_array=array_to_reshape.reshape(3,4)
print(reshaped_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
broad_array1=np.array([[1,2,3],[4,5,6]])
broad_array2=np.array([10,20,30])
print(broad_array1+broad_array2)

[[11 22 33]
 [14 25 36]]


In [44]:
broad_array3=np.array([[1,2,3],[4,5,6]])
broad_array4=np.array([[10,20,30],[15,25,35]])
print(broad_array3+broad_array4)

[[11 22 33]
 [19 30 41]]


In [46]:
struc_array1=np.array([('sana',20,60.5),('Mansi',21,62.3)],
                      dtype=[('name',(np.str_,10)),('age',np.int32),('weight',np.float64)])

In [47]:
struc_array1

array([('sana', 20, 60.5), ('Mansi', 21, 62.3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [48]:
print(struc_array1['name'])

['sana' 'Mansi']


In [53]:
print(struc_array1['age'])

[20 21]


In [54]:
print(struc_array1['weight'])

[60.5 62.3]


In [56]:
struc_array2=np.sort(struc_array1,order='name')
print("sorting according to name",struc_array2)

sorting according to name [('Mansi', 21, 62.3) ('sana', 20, 60.5)]


In [57]:
arr=np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [58]:
arr=np.array([1,2,3,4,5])
x = arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [62]:
original_array1=np.array([1,2,3,4,5])
print("Original array",original_array1)
view_array=original_array.view()
original_array1[0]=42
print("After updation")
print(original_array1)
print(view_array)

Original array [1 2 3 4 5]
After updation
[42  2  3  4  5]
[1 2 3 4 5 4 4]


In [1]:
import numpy as np

In [4]:
#Exercise 1:
#Create a numpy array with 5 elements consisting of random integers between 1 and 100.
array1=np.array([14,56,78,95,45])
array1=np.random.randint(1,101,size=5)
print(array1)

[13 58 57 22 53]


In [5]:
#Exercise 2:
#Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
array2=np.array([1,2,3,4,5,6,7,8,9,10])
array2=np.arange(1,11).reshape(2,5)
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
#Exercise 3:
#Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.
array3=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
array3=np.arange(1,21)
subarray3=array3[4:15]
print(subarray3)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [9]:
#Exercise 4:
#Create a numpy array with 10 elements consisting of evenly spaced numbers between 0 and 1.
array4=np.array([12,45,34,67,12,3,4,6,7,8])
array4=np.linspace(0,1,num=10)
print(array4)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
#Exercise 5:
#Create a numpy array containing the numbers from 1 to 9, and then square each element in the array
array5=np.array([1,2,3,4,5,6,7,8,9])
array5=np.arange(1,10)
squared_array5=np.square(array5)
print(squared_array5)

[ 1  4  9 16 25 36 49 64 81]


# trigonometric function

#### conversion of degree into radians

In [1]:
import numpy as np

In [3]:
angles=np.array([0,30,45,60,90,180])
radiaus=np.deg2rad(angles)
print(radiaus)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]


In [5]:
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(np.sin(radians))

Sine of angles in the array:


NameError: name 'radians' is not defined